apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-1
  template:
    metadata:
      labels:
        app: webapp-1
    spec:
      containers:
      - image: mywebapp:1.0.0
        name: mywebapp-1
        ports:
        - containerPort: 8080

