apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: mywebapp:1.0.0
        name: mywebapp
        ports:
        - containerPort: 8080

