apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-2
  template:
    metadata:
      labels:
        app: webapp-2
    spec:
      containers:
      - image: mywebapp:1.0.0
        name: webapp-2
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: webapp

